<?php

use Illuminate\Database\Seeder;

class Default_CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

        $records = array(
            ['id'=>1,'name'=>'Afghanistan', 'description'=>''],
            ['id'=>2,'name'=>'Algeria', 'description'=>''],
            ['id'=>3,'name'=>'Andorra', 'description'=>''],
            ['id'=>4,'name'=>'Angola', 'description'=>''],
            ['id'=>5,'name'=>'Antigua and Barbuda', 'description'=>''],
            ['id'=>6,'name'=>'Argentina', 'description'=>''],
            ['id'=>7,'name'=>'Armenia', 'description'=>''],
            ['id'=>8,'name'=>'Australia', 'description'=>''],
            ['id'=>9,'name'=>'Austria', 'description'=>''],
            ['id'=>10,'name'=>'Azerbaijan', 'description'=>''],
            ['id'=>11,'name'=>'Bahamas', 'description'=>''],
            ['id'=>12,'name'=>'Bahrain', 'description'=>''],
            ['id'=>13,'name'=>'Bangladesh', 'description'=>''],
            ['id'=>14,'name'=>'Barbados', 'description'=>''],
            ['id'=>15,'name'=>'Belarus', 'description'=>''],
            ['id'=>16,'name'=>'Belgium', 'description'=>''],
            ['id'=>17,'name'=>'Belize', 'description'=>''],
            ['id'=>18,'name'=>'Benin', 'description'=>''],
            ['id'=>19,'name'=>'Bhutan', 'description'=>''],
            ['id'=>20,'name'=>'Bolivia', 'description'=>''],
            ['id'=>21,'name'=>'Bosnia and Herzegovina', 'description'=>''],
            ['id'=>22,'name'=>'Botswana', 'description'=>''],
            ['id'=>23,'name'=>'Brazil', 'description'=>''],
            ['id'=>24,'name'=>'Brunei Darussalam', 'description'=>''],
            ['id'=>25,'name'=>'Bulgaria', 'description'=>''],
            ['id'=>26,'name'=>'Burkina Faso', 'description'=>''],
            ['id'=>27,'name'=>'Burundi', 'description'=>''],
            ['id'=>28,'name'=>'Cabo Verde', 'description'=>''],
            ['id'=>29,'name'=>'Cambodia', 'description'=>''],
            ['id'=>30,'name'=>'Cameroon', 'description'=>''],
            ['id'=>31,'name'=>'Canada', 'description'=>''],
            ['id'=>32,'name'=>'Central African Republic', 'description'=>''],
            ['id'=>33,'name'=>'Chad', 'description'=>''],
            ['id'=>34,'name'=>'Chile', 'description'=>''],
            ['id'=>35,'name'=>'China', 'description'=>''],
            ['id'=>36,'name'=>'Colombia', 'description'=>''],
            ['id'=>37,'name'=>'Comoros', 'description'=>''],
            ['id'=>38,'name'=>'Congo', 'description'=>''],
            ['id'=>39,'name'=>'Costa Rica', 'description'=>''],
            ['id'=>40,'name'=>"Côte d'Ivoire", 'description'=>''],
            ['id'=>41,'name'=>'Croatia', 'description'=>''],
            ['id'=>42,'name'=>'Cuba', 'description'=>''],
            ['id'=>43,'name'=>'Cyprus', 'description'=>''],
            ['id'=>44,'name'=>'Czech Republic', 'description'=>''],
            ['id'=>45,'name'=>'Democratic People Republic of Korea (North Korea)', 'description'=>''],
            ['id'=>46,'name'=>'Democratic Republic of the Cong', 'description'=>''],
            ['id'=>47,'name'=>'Denmark', 'description'=>''],
            ['id'=>48,'name'=>'Djibouti', 'description'=>''],
            ['id'=>49,'name'=>'Dominica', 'description'=>''],
            ['id'=>50,'name'=>'Dominican Republic', 'description'=>''],
            ['id'=>51,'name'=>'Ecuador', 'description'=>''],
            ['id'=>52,'name'=>'Egypt', 'description'=>''],
            ['id'=>53,'name'=>'El Salvador', 'description'=>''],
            ['id'=>54,'name'=>'Equatorial Guinea', 'description'=>''],
            ['id'=>55,'name'=>'Eritrea', 'description'=>''],
            ['id'=>56,'name'=>'Estonia', 'description'=>''],
            ['id'=>57,'name'=>'Ethiopia', 'description'=>''],
            ['id'=>58,'name'=>'Fiji', 'description'=>''],
            ['id'=>59,'name'=>'Finland', 'description'=>''],
            ['id'=>60,'name'=>'France', 'description'=>''],
            ['id'=>61,'name'=>'Gabon', 'description'=>''],
            ['id'=>62,'name'=>'Gambia', 'description'=>''],
            ['id'=>63,'name'=>'Georgia', 'description'=>''],
            ['id'=>64,'name'=>'Germany', 'description'=>''],
            ['id'=>65,'name'=>'Ghana', 'description'=>''],
            ['id'=>66,'name'=>'Greece', 'description'=>''],
            ['id'=>67,'name'=>'Grenada', 'description'=>''],
            ['id'=>68,'name'=>'Guatemala', 'description'=>''],
            ['id'=>69,'name'=>'Guinea', 'description'=>''],
            ['id'=>70,'name'=>'Guinea-Bissau', 'description'=>''],
            ['id'=>71,'name'=>'Guyana', 'description'=>''],
            ['id'=>72,'name'=>'Haiti', 'description'=>''],
            ['id'=>73,'name'=>'Honduras', 'description'=>''],
            ['id'=>74,'name'=>'Hungary', 'description'=>''],
            ['id'=>75,'name'=>'Iceland', 'description'=>''],
            ['id'=>76,'name'=>'India', 'description'=>''],
            ['id'=>77,'name'=>'Indonesia', 'description'=>''],
            ['id'=>78,'name'=>'Iran', 'description'=>''],
            ['id'=>79,'name'=>'Iraq', 'description'=>''],
            ['id'=>80,'name'=>'Ireland', 'description'=>''],
            ['id'=>81,'name'=>'Israel', 'description'=>''],
            ['id'=>82,'name'=>'Italy', 'description'=>''],
            ['id'=>83,'name'=>'Jamaica', 'description'=>''],
            ['id'=>84,'name'=>'Japan', 'description'=>''],
            ['id'=>85,'name'=>'Joran', 'description'=>''],
            ['id'=>86,'name'=>'Kazakhstan', 'description'=>''],
            ['id'=>87,'name'=>'Kenya', 'description'=>''],
            ['id'=>88,'name'=>'Kiribati', 'description'=>''],
            ['id'=>89,'name'=>'Kuwait', 'description'=>''],
            ['id'=>90,'name'=>'Kyrgyzstan', 'description'=>''],
            ['id'=>91,'name'=>'Lao People Democratic Republic (Laos)', 'description'=>''],
            ['id'=>92,'name'=>'Latvia', 'description'=>''],
            ['id'=>93,'name'=>'Lebanon', 'description'=>''],
            ['id'=>94,'name'=>'Lesotho', 'description'=>''],
            ['id'=>95,'name'=>'Liberia', 'description'=>''],
            ['id'=>96,'name'=>'Libya', 'description'=>''],
            ['id'=>97,'name'=>'Liechtenstein', 'description'=>''],
            ['id'=>98,'name'=>'Lithuania', 'description'=>''],
            ['id'=>99,'name'=>'Luxembourg', 'description'=>''],
            ['id'=>100,'name'=>'Macedonia', 'description'=>''],
            ['id'=>101,'name'=>'Madagascar', 'description'=>''],
            ['id'=>102,'name'=>'Malawi', 'description'=>''],
            ['id'=>103,'name'=>'Malaysia', 'description'=>''],
            ['id'=>104,'name'=>'Maldives', 'description'=>''],
            ['id'=>105,'name'=>'Mali', 'description'=>''],
            ['id'=>106,'name'=>'Malta', 'description'=>''],
            ['id'=>107,'name'=>'Marshall Islands', 'description'=>''],
            ['id'=>108,'name'=>'Mauritania', 'description'=>''],
            ['id'=>109,'name'=>'Mauritius', 'description'=>''],
            ['id'=>110,'name'=>'Mexico', 'description'=>''],
            ['id'=>111,'name'=>'Micronesia (Federated States of)', 'description'=>''],
            ['id'=>112,'name'=>'Monaco', 'description'=>''],
            ['id'=>113,'name'=>'Mongolia', 'description'=>''],
            ['id'=>114,'name'=>'Montenegro', 'description'=>''],
            ['id'=>115,'name'=>'Morocco', 'description'=>''],
            ['id'=>116,'name'=>'Mozambique', 'description'=>''],
            ['id'=>117,'name'=>'Myanmar', 'description'=>''],
            ['id'=>118,'name'=>'Namibia', 'description'=>''],
            ['id'=>119,'name'=>'Nauru', 'description'=>''],
            ['id'=>120,'name'=>'Nepal', 'description'=>''],
            ['id'=>121,'name'=>'Netherlands', 'description'=>''],
            ['id'=>122,'name'=>'New Zealand', 'description'=>''],
            ['id'=>123,'name'=>'Nicaragua', 'description'=>''],
            ['id'=>124,'name'=>'Niger', 'description'=>''],
            ['id'=>125,'name'=>'Nigeria', 'description'=>''],
            ['id'=>126,'name'=>'Norway', 'description'=>''],
            ['id'=>127,'name'=>'Oman', 'description'=>''],
            ['id'=>128,'name'=>'Pakistan', 'description'=>''],
            ['id'=>129,'name'=>'Palau', 'description'=>''],
            ['id'=>130,'name'=>'Panama', 'description'=>''],
            ['id'=>131,'name'=>'Papua New Guinea', 'description'=>''],
            ['id'=>132,'name'=>'Paraguay', 'description'=>''],
            ['id'=>133,'name'=>'Peru', 'description'=>''],
            ['id'=>134,'name'=>'Philippines', 'description'=>''],
            ['id'=>135,'name'=>'Poland', 'description'=>''],
            ['id'=>136,'name'=>'Portugal', 'description'=>''],
            ['id'=>137,'name'=>'Qatar', 'description'=>''],
            ['id'=>138,'name'=>'Republic of Moldova', 'description'=>''],
            ['id'=>139,'name'=>'Romania', 'description'=>''],
            ['id'=>140,'name'=>'Russian Federation', 'description'=>''],
            ['id'=>141,'name'=>'Rwanda', 'description'=>''],
            ['id'=>142,'name'=>'Saint Kitts and Nevis', 'description'=>''],
            ['id'=>143,'name'=>'Saint Lucia', 'description'=>''],
            ['id'=>144,'name'=>'Saint Vincent and the Grenadines', 'description'=>''],
            ['id'=>145,'name'=>'Samoa', 'description'=>''],
            ['id'=>146,'name'=>'San Marino', 'description'=>''],
            ['id'=>147,'name'=>'Sao Tome and Principe', 'description'=>''],
            ['id'=>148,'name'=>'Saudi Arabia', 'description'=>''],
            ['id'=>149,'name'=>'Senegal', 'description'=>''],
            ['id'=>150,'name'=>'Serbia', 'description'=>''],
            ['id'=>151,'name'=>'Seychelles', 'description'=>''],
            ['id'=>152,'name'=>'Sierra Leone', 'description'=>''],
            ['id'=>153,'name'=>'Singapore', 'description'=>''],
            ['id'=>154,'name'=>'Slovakia', 'description'=>''],
            ['id'=>155,'name'=>'Slovenia', 'description'=>''],
            ['id'=>156,'name'=>'Solomon Islands', 'description'=>''],
            ['id'=>157,'name'=>'Somalia', 'description'=>''],
            ['id'=>158,'name'=>'South Africa', 'description'=>''],
            ['id'=>159,'name'=>'South Korea', 'description'=>''],
            ['id'=>160,'name'=>'South Sudan', 'description'=>''],
            ['id'=>161,'name'=>'Spain', 'description'=>''],
            ['id'=>162,'name'=>'Sri Lanka', 'description'=>''],
            ['id'=>163,'name'=>'Sudan', 'description'=>''],
            ['id'=>164,'name'=>'Suriname', 'description'=>''],
            ['id'=>165,'name'=>'Swaziland', 'description'=>''],
            ['id'=>166,'name'=>'Sweden', 'description'=>''],
            ['id'=>167,'name'=>'Switzerland', 'description'=>''],
            ['id'=>168,'name'=>'Syrian Arab Republic', 'description'=>''],
            ['id'=>169,'name'=>'Tajikistan', 'description'=>''],
            ['id'=>170,'name'=>'Thailand', 'description'=>''],
            ['id'=>171,'name'=>'Timor-Leste', 'description'=>''],
            ['id'=>172,'name'=>'Togo', 'description'=>''],
            ['id'=>173,'name'=>'Tonga', 'description'=>''],
            ['id'=>174,'name'=>'Trinidad and Tobago', 'description'=>''],
            ['id'=>175,'name'=>'Tunisia', 'description'=>''],
            ['id'=>176,'name'=>'Turkey', 'description'=>''],
            ['id'=>177,'name'=>'Turkmenistan', 'description'=>''],
            ['id'=>178,'name'=>'Tuvalu', 'description'=>''],
            ['id'=>179,'name'=>'Uganda', 'description'=>''],
            ['id'=>180,'name'=>'Ukraine', 'description'=>''],
            ['id'=>181,'name'=>'United Arab Emirates', 'description'=>''],
            ['id'=>182,'name'=>'United Kingdom of Great Britain and Northern Ireland', 'description'=>''],
            ['id'=>183,'name'=>'United Republic of Tanzania', 'description'=>''],
            ['id'=>184,'name'=>'United States of America', 'description'=>''],
            ['id'=>185,'name'=>'Uruguay', 'description'=>''],
            ['id'=>186,'name'=>'Uzbekistan', 'description'=>''],
            ['id'=>187,'name'=>'Vanuatu', 'description'=>''],
            ['id'=>188,'name'=>'Venezuela', 'description'=>''],
            ['id'=>189,'name'=>'Vietnam', 'description'=>''],
            ['id'=>190,'name'=>'Yemen', 'description'=>''],
            ['id'=>191,'name'=>'Zambia', 'description'=>''],
            ['id'=>192,'name'=>'Zimbabwe', 'description'=>''],

        );

        DB::table('countries')->insert($records);
    }
}
